# -*- coding: utf-8 -*-
"""servidor_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLPBLhcOp9Gr6U2ZbEfdpZQ-WW2Yth5o
"""

# Commented out IPython magic to ensure Python compatibility.
# %mkdir templates -p

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/index.html
# 
# <html>
#   <head>
#       <style>
#         body{
#           background-color : lightblue;
#         }
#       </style>
#    </head>
#   <body>
#     <h1>Flask</h1>
#   </body>
# </html>

import os
import threading

!pip install pyngrok

from flask import Flask, render_template
from pyngrok import ngrok

app = Flask(__name__)
app.debug = True  # Set debug mode for development
port = 8082
ngrok.set_auth_token("2g7E7GNoDzDBvfJC9nagmKo65qs_7fXuC17Woi3JKmCHNy2Tc")
public_url = ngrok.connect(port).public_url
#print(" * ngrok \"{}" - \"http://127.0.0.1:{}\"".format(public_url, port))
app.config["BASE_URL"] = public_url
print("public_url: " +  public_url)

@app.route("/get")
def index():
  return render_template("index.html")

threading.Thread(target=app.run).start()

